### ISSUE TITLE
doesn't hide tabs in all panes

### ISSUE THREAD

**Issue by coleleahy** [gianmarcotoso/atom-hide-tabs#1]
With two or more tabs open, the atom-hide-tabs:toggle command only toggles tabs for the topmost-leftmost pane.

**Comment by gianmarcotoso** [comment]
Thank you! I'll get to it as soon as I can, but you're welcome to make a
pull request if you feel so inclined! :)

**Comment by pnevyk** [comment]
Closed by #3
